services:
  blockchain:
    image: blockchain
    container_name: blockchain_server
    build: 
      context: ./blockchain
    ports:
      - "8545:8545"    # RPC port
      - "30303:30303"  # P2P port
    networks:
      - devnet
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/16/docker
    volumes:
      - pgdata:/var/lib/postgresql/16/docker
      - ./database/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - devnet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - devnet
  
  backend:
    image: backend
    container_name: backend_server
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - blockchain
    # Solution for dev purposes
    volumes:
      - ./blockchain/artifacts/contracts:/blockchain/artifacts/contracts
    env_file:
      - ./backend/.env
    environment:
      RPC_URL: http://blockchain:8545
    networks:
      - devnet


volumes:
  pgdata:

networks:
  devnet:
