version: "3.9"
services:
  blockchain:
    build:
      context: .
      target: blockchain-stage
    container_name: blockchain_node
    ports:
      - "8545:8545"
      - "30303:30303"
    # command: anvil --host 0.0.0.0
    # command: wake up 
    command: anvil --host 0.0.0.0 --port 8545




  backend:
    build:
      context: .
      target: backend-stage
    container_name: backend_server
    ports:
      - "8000:8000"
    depends_on:
      - blockchain
    environment:
      PYTHONPATH: /app/blockchain/pytypes
      BLOCKCHAIN_RPC: http://blockchain:8545




# services:
#   blockchain-base:
#     build:
#       context: ./docker_base
#     image: blockchain-base

#   blockchain:
#     build: ./blockchain
#     container_name: blockchain_node
#     ports:
#       - "8545:8545"
#       - "30303:30303"
#     depends_on:
#       - blockchain-base

#   backend:
#     build: ./backend
#     container_name: backend_server
#     ports:
#       - "8000:8000"
#     depends_on:
#       - blockchain
#       - blockchain-base
#     environment:
#       PYTHONPATH: /app/pytypes

  # database:
  #   image: postgres:15
  #   container_name: coupon_db
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: coupons
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
