[compiler.solc]
exclude_paths = ["lib", ".venv", "node_modules", "scripts", "venv", "tests"]
include_paths = ["node_modules"]

[compiler.solc.optimizer]
runs = 200

[detectors]
exclude = []
ignore_paths = ["venv", ".venv", "test"]
exclude_paths = ["lib", ".venv", "node_modules", "scripts", "venv", "tests"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""

[python]
out_dir = "pytypes"
